version: '3'

services:
  #============================================================================
  spark-master:
   image: bde2020/spark-master:3.0.2-hadoop3.2
   container_name: spark-master
   ports:
     - "8080:8080"
     - "7077:7077"
   environment:
     - INIT_DAEMON_STEP=setup_spark
  #============================================================================
  spark-worker-1:
   image: bde2020/spark-worker:3.0.2-hadoop3.2
   container_name: spark-worker-1
   depends_on:
     - spark-master
   ports:
     - "8081:8081"
   environment:
     - "SPARK_MASTER=spark://spark-master:7077"
  #============================================================================
  spark-worker-2:
   image: bde2020/spark-worker:3.0.2-hadoop3.2
   container_name: spark-worker-2
   depends_on:
     - spark-master
   ports:
     - "8082:8082"
   environment:
     - "SPARK_MASTER=spark://spark-master:7077"
     - "SPARK_WORKER_CORES=1"
     - "SPARK_WORKER_MEMORY=1G"
  #============================================================================
  spark-submit-training:
   image: minkal/spark-submit-detection
   container_name: spark-detection-training
   depends_on:
     - spark-master
     - spark-worker-1
     - spark-worker-2
   environment:
     SPARK_APPLICATION_MAIN_CLASS: intrusionDetection.testRW
     SPARK_APPLICATION_ARGS: "${DATASET_LOCATION}/${TRAINING_FILE} ${MODELS_LOCATION}"
     SPARK_SUBMIT_ARGS: "${SPARK_TRAIN_ARGUMENTS}"
     ENABLE_INIT_DAEMON: "false"
  #============================================================================
  #============================================================================